name: 'Terraform Apply'
description: 'Run Terraform Apply'
inputs:
  working_directory:  
    description: 'The directory where the Terraform configuration is located.'
    required: true
    default: .

runs:
  using: "composite"
  steps:    
    - name: Terraform Apply
      run: |
         terraform apply --auto-approve 
      working-directory: ${{ inputs.working_directory }}
      shell: bash
